import { AgentResponse, ChatMessage } from '../dispatcher';
import { getChatResponse } from '../chatAgent';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

// ─── Constants ─────────────────────────────────────────────────────────────
const PAGE_WIDTH = 595.28; // A4
const PAGE_HEIGHT = 841.89; // A4
const MARGIN = 50;

const COLORS = {
  titleBlue: rgb(30 / 255, 58 / 255, 138 / 255),
  headingBlue: rgb(37 / 255, 99 / 255, 235 / 255),
  body: rgb(55 / 255, 65 / 255, 81 / 255),
  muted: rgb(107 / 255, 114 / 255, 128 / 255),
  accent: rgb(219 / 255, 234 / 255, 254 / 255),
};

// ─── Build PDF buffer ──────────────────────────────────────────────────────
async function buildPdfBuffer(title: string, content: string, date: string): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let cursorY = PAGE_HEIGHT - MARGIN;

  const checkPageBreak = (neededHeight: number) => {
    if (cursorY - neededHeight < MARGIN) {
      page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      cursorY = PAGE_HEIGHT - MARGIN;
    }
  };

  const wrapText = (text: string, maxWidth: number, font: any, fontSize: number): string[] => {
    const words = text.split(' ');
    const lines: string[] = [];
    let currentLine = words[0] || '';
    for (let i = 1; i < words.length; i++) {
      const word = words[i];
      const width = font.widthOfTextAtSize(currentLine + ' ' + word, fontSize);
      if (width < maxWidth) {
        currentLine += ' ' + word;
      } else {
        lines.push(currentLine);
        currentLine = word;
      }
    }
    if (currentLine) lines.push(currentLine);
    return lines;
  };

  const drawText = (text: string, font: any, size: number, color: any, xOffset = 0) => {
    const maxWidth = PAGE_WIDTH - MARGIN * 2 - xOffset;
    const wrappedLines = wrapText(text, maxWidth, font, size);
    for (const line of wrappedLines) {
      checkPageBreak(size * 1.5);
      page.drawText(line, { x: MARGIN + xOffset, y: cursorY - size, size, font, color });
      cursorY -= size * 1.5;
    }
  };

  // ── Header ──────────────────────────────────────────────────────────────
  drawText(title, fontBold, 22, COLORS.titleBlue);
  cursorY += 5;
  drawText(`Generated by Synthox AI  •  ${date}`, fontRegular, 9, COLORS.muted);
  cursorY -= 10;
  page.drawLine({
    start: { x: MARGIN, y: cursorY },
    end: { x: PAGE_WIDTH - MARGIN, y: cursorY },
    thickness: 2,
    color: COLORS.titleBlue,
  });
  cursorY -= 20;

  // ── Body ────────────────────────────────────────────────────────────────
  const bodyLines = content.split('\n');
  for (const line of bodyLines) {
    const trimmed = line.trim();
    if (!trimmed) { cursorY -= 10; continue; }

    const clean = trimmed
      .replace(/\*\*(.*?)\*\*/g, '$1')
      .replace(/\*(.*?)\*/g, '$1')
      .replace(/`(.*?)`/g, '$1');

    if (trimmed.startsWith('# ')) {
      cursorY -= 10;
      drawText(clean.slice(2), fontBold, 14, COLORS.headingBlue);
      cursorY += 5;
      page.drawLine({
        start: { x: MARGIN, y: cursorY },
        end: { x: PAGE_WIDTH - MARGIN, y: cursorY },
        thickness: 1,
        color: COLORS.accent,
      });
      cursorY -= 10;
    } else if (trimmed.startsWith('## ')) {
      cursorY -= 5;
      drawText(clean.slice(3), fontBold, 12, COLORS.titleBlue);
    } else if (trimmed.startsWith('### ')) {
      drawText(clean.slice(4), fontBold, 11, COLORS.body);
    } else if (trimmed.startsWith('* ') || trimmed.startsWith('- ')) {
      drawText(`•  ${clean.slice(2)}`, fontRegular, 11, COLORS.body, 15);
    } else {
      drawText(clean, fontRegular, 11, COLORS.body);
    }
  }

  // ── Footer ───────────────────────────────────────────────────────────────
  const pages = pdfDoc.getPages();
  pages.forEach((p, idx) => {
    const footerY = MARGIN - 20;
    p.drawLine({
      start: { x: MARGIN, y: footerY + 15 },
      end: { x: PAGE_WIDTH - MARGIN, y: footerY + 15 },
      thickness: 1,
      color: rgb(229 / 255, 231 / 255, 235 / 255),
    });
    p.drawText('Synthox AI — Confidential', {
      x: MARGIN, y: footerY, size: 9, font: fontRegular, color: COLORS.muted,
    });
    const pageNumText = `${idx + 1} / ${pages.length}`;
    const pageNumWidth = fontRegular.widthOfTextAtSize(pageNumText, 9);
    p.drawText(pageNumText, {
      x: PAGE_WIDTH - MARGIN - pageNumWidth, y: footerY, size: 9, font: fontRegular, color: COLORS.muted,
    });
  });

  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes);
}

// ─── Agent Entry Point ─────────────────────────────────────────────────────
export async function runPdfAgent(query: string, context: ChatMessage[], userId: string): Promise<AgentResponse> {
  try {
    console.log(`[PdfAgent] Preparing content...`);

    const synthesisPrompt = `You are a helpful assistant exporting a conversation to a PDF document.
The user asked: "${query}"

Write a clean, well-structured summary using ONLY the following Markdown:
- # for main headings
- ## for sub-headings
- ### for sub-sub-headings
- * item for bullet points
- Plain paragraphs for body text

Do NOT use HTML tags, code blocks, or any other formatting. Keep it concise but comprehensive.`;

    const chatContext = [...context, { role: 'user' as const, content: synthesisPrompt }];
    const synthesisRes = await getChatResponse(chatContext, 'PdfAgent');
    const markdownContent = synthesisRes.content;

    const titleMatch = markdownContent.match(/^#\s+(.+)/m);
    const docTitle = titleMatch ? titleMatch[1].trim() : 'Synthox AI Export';
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

    console.log(`[PdfAgent] Rendering PDF with pdf-lib...`);
    const pdfBuffer = await buildPdfBuffer(docTitle, markdownContent, date);
    console.log(`[PdfAgent] PDF generated (${Math.round(pdfBuffer.length / 1024)} KB)`);

    // Return as base64 data URI — the ChatWindow converts this to a blob: URL before showing in the iframe
    const base64Pdf = pdfBuffer.toString('base64');
    const fileUrl = `data:application/pdf;base64,${base64Pdf}`;

    return {
      agentType: 'pdf_generation',
      content: `✅ Your PDF **"${docTitle}"** is ready! Click the button below to view it in the document viewer.`,
      fileUrl,
      status: 'success',
    };
  } catch (error) {
    console.error(`[PdfAgent] Error:`, error);
    return {
      agentType: 'pdf_generation',
      content: `⚠️ Failed to generate PDF: ${(error as Error).message}`,
      status: 'error',
    };
  }
}
